### ISSUE TITLE
syntax error near unexpected token `0.23'

### ISSUE THREAD

**Issue by onionstack** [kendryte/openocd-kendryte#1]
checking for makeinfo... makeinfo
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for ranlib... ranlib
./configure: line 4593: syntax error near unexpected token `0.23'
./configure: line 4593: `PKG_PROG_PKG_CONFIG(0.23)'

**Comment by minux** [comment]
Did you run `bootstrap` before running the configure script?
It seems your configure script is not generated correctly.

**Comment by Alinshans** [comment]
@DF-LeeX 
What is your build environment?
Maybe you need to reinstall pkg-config and libtool, have a try!

**Comment by Alinshans** [comment]
This problem seems to be solved.

**Comment by onionstack** [comment]
@Alinshans 
Ok, thank you. I've run it successfully

**Comment by djankins-rypos** [comment]
I have the same problem.
How did this get solved
thanks

**Comment by cropse** [comment]
@djankins-rypos try reinstall or install like this, work for me:
`apt install pkg-config libtool`
